/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import controller.*;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import model.*;
import javax.swing.JOptionPane;
import dao.phieu_muon_dao;
/**
 *
 * @author minh0
 */
public class fm_doc_gia extends javax.swing.JPanel {
    private List<doc_gia> docgiaList;
    private List<listpm> pmList;
    
    public fm_doc_gia() {
        initComponents();
        initTP();
    }
    public void initTP(){
        doc_gia_control.getdg_con().load_cb_gt(cb_gioi_tinh_tk);
        doc_gia_control.getdg_con().load_cb_tt(cb_trang_thai_tk);
        doc_gia_control.getdg_con().load_cb_tt(cb_trang_thai_tt);
        Calendar cl = Calendar.getInstance();
        dc_nSinh_tt.setDate(cl.getTime());
        docgiaList = doc_gia_control.getdg_con().timkiemdg("","","",2,"","", "","");
        doc_gia_control.getdg_con().load_list_tbl(tbl_DS_doc_gia, docgiaList);
        lich_su_muon_tra.setLocationRelativeTo(null);
        lich_su_muon_tra.setSize(600, 400);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lich_su_muon_tra = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        txt_dg_pm = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_ten_dg_pm = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_dsPM = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_ma_doc_gia_tt = new javax.swing.JTextField();
        txt_ten_doc_gia_tt = new javax.swing.JTextField();
        txt_CCCD_tt = new javax.swing.JTextField();
        txt_SDT_tt = new javax.swing.JTextField();
        bt_them_dg = new javax.swing.JButton();
        bt_luu_dg = new javax.swing.JButton();
        bt_xoa_dg = new javax.swing.JButton();
        bt_huy_dg = new javax.swing.JButton();
        rb_nam = new javax.swing.JRadioButton();
        rb_nu = new javax.swing.JRadioButton();
        txt_dia_chi_tt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cb_trang_thai_tt = new javax.swing.JComboBox<>();
        dc_nSinh_tt = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_ma_doc_gia_tk = new javax.swing.JTextField();
        txt_ten_doc_gia_tk = new javax.swing.JTextField();
        txt_CCCD_tk = new javax.swing.JTextField();
        txt_SDT_tk = new javax.swing.JTextField();
        bt_tk_doc_gia = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txt_dia_chi_tk = new javax.swing.JTextField();
        cb_trang_thai_tk = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        bt_lam_moi = new javax.swing.JButton();
        cb_gioi_tinh_tk = new javax.swing.JComboBox<>();
        txt_nSinh_tk = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_DS_doc_gia = new javax.swing.JTable();

        lich_su_muon_tra.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        lich_su_muon_tra.setTitle("Lịch sử mượn trả");
        lich_su_muon_tra.setAlwaysOnTop(true);
        lich_su_muon_tra.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jLabel17.setText("Mã độc giả");

        jLabel18.setText("Tên độc giả");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách phiếu mượn"));

        tbl_dsPM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu mượn", "Ngày lập phiếu", "Ngày trả phiếu", "Số lượng sách", "Trạng thái"
            }
        ));
        jScrollPane2.setViewportView(tbl_dsPM);

        javax.swing.GroupLayout lich_su_muon_traLayout = new javax.swing.GroupLayout(lich_su_muon_tra.getContentPane());
        lich_su_muon_tra.getContentPane().setLayout(lich_su_muon_traLayout);
        lich_su_muon_traLayout.setHorizontalGroup(
            lich_su_muon_traLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lich_su_muon_traLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lich_su_muon_traLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(lich_su_muon_traLayout.createSequentialGroup()
                        .addGroup(lich_su_muon_traLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(lich_su_muon_traLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_dg_pm)
                            .addComponent(txt_ten_dg_pm, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        lich_su_muon_traLayout.setVerticalGroup(
            lich_su_muon_traLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lich_su_muon_traLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(lich_su_muon_traLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_dg_pm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lich_su_muon_traLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_ten_dg_pm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("Mã độc giả ");

        jLabel3.setText("Tên độc giả");

        jLabel4.setText("Số CCCD");

        jLabel5.setText("Giới tính");

        jLabel6.setText("Ngày sinh");

        jLabel7.setText("SĐT");

        jLabel8.setText("Địa chỉ");

        bt_them_dg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/add.png"))); // NOI18N
        bt_them_dg.setText("Thêm");
        bt_them_dg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_them_dgActionPerformed(evt);
            }
        });

        bt_luu_dg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/save.png"))); // NOI18N
        bt_luu_dg.setText("Lưu");
        bt_luu_dg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_luu_dgActionPerformed(evt);
            }
        });

        bt_xoa_dg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/delete.png"))); // NOI18N
        bt_xoa_dg.setText("Xóa");
        bt_xoa_dg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xoa_dgActionPerformed(evt);
            }
        });

        bt_huy_dg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/refresh.png"))); // NOI18N
        bt_huy_dg.setText("Hủy");
        bt_huy_dg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_huy_dgActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_nam);
        rb_nam.setSelected(true);
        rb_nam.setText("Nam");

        buttonGroup1.add(rb_nu);
        rb_nu.setText("Nữ");
        rb_nu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Trạng thái");

        cb_trang_thai_tt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Được mượn sách", "Đang mượn sách", "Quá hạn mượn", "Không cho mượn" }));

        dc_nSinh_tt.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_ten_doc_gia_tt, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(txt_ma_doc_gia_tt)
                            .addComponent(txt_CCCD_tt)))
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(rb_nam)
                        .addGap(50, 50, 50)
                        .addComponent(rb_nu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_SDT_tt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_dia_chi_tt)
                    .addComponent(cb_trang_thai_tt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dc_nSinh_tt, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bt_them_dg)
                    .addComponent(bt_luu_dg)
                    .addComponent(bt_xoa_dg)
                    .addComponent(bt_huy_dg))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bt_huy_dg, bt_luu_dg, bt_them_dg, bt_xoa_dg});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dc_nSinh_tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_ten_doc_gia_tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txt_SDT_tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_CCCD_tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(bt_them_dg)
                            .addComponent(txt_ma_doc_gia_tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(bt_luu_dg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_xoa_dg)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_dia_chi_tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(rb_nam)
                            .addComponent(rb_nu)
                            .addComponent(cb_trang_thai_tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_huy_dg)
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bt_huy_dg, bt_them_dg, bt_xoa_dg});

        jTabbedPane1.addTab("Thông tin độc giả", jPanel1);

        jLabel9.setText("Mã độc giả");

        jLabel10.setText("Tên độc giả");

        jLabel11.setText("Số CCCD");

        jLabel12.setText("Giới tính");

        jLabel13.setText("Ngày sinh");

        jLabel14.setText("SĐT");

        bt_tk_doc_gia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/xemdiem.png"))); // NOI18N
        bt_tk_doc_gia.setText("Tìm kiếm");
        bt_tk_doc_gia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tk_doc_giaActionPerformed(evt);
            }
        });

        jLabel15.setText("Địa chỉ");

        cb_trang_thai_tk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "Được mượn sách", "Đang mượn sách", "Quá hạn mượn", "Không cho mượn" }));

        jLabel16.setText("Trạng thái");

        bt_lam_moi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/refresh.png"))); // NOI18N
        bt_lam_moi.setText("Làm mới");
        bt_lam_moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_lam_moiActionPerformed(evt);
            }
        });

        cb_gioi_tinh_tk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "Nam", "Nữ" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ma_doc_gia_tk, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ten_doc_gia_tk, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_CCCD_tk, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_gioi_tinh_tk, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_dia_chi_tk)
                    .addComponent(txt_SDT_tk)
                    .addComponent(cb_trang_thai_tk, 0, 245, Short.MAX_VALUE)
                    .addComponent(txt_nSinh_tk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_tk_doc_gia, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(bt_lam_moi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel13, jLabel14});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12, jLabel9});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cb_gioi_tinh_tk, txt_CCCD_tk, txt_ma_doc_gia_tk, txt_ten_doc_gia_tk});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_ma_doc_gia_tk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_ten_doc_gia_tk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txt_nSinh_tk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt_SDT_tk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_tk_doc_gia))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_CCCD_tk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txt_dia_chi_tk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_lam_moi))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(cb_gioi_tinh_tk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_trang_thai_tk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tìm kiếm độc giả", jPanel2);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách độc giả", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 10))); // NOI18N

        tbl_DS_doc_gia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã độc giả", "Tên độc giả", "Số CCCD", "Giới tính", "Ngày sinh", "SĐT", "Địa chỉ", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_DS_doc_gia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DS_doc_giaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_DS_doc_gia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_lam_moiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_lam_moiActionPerformed
        txt_ma_doc_gia_tk.setText("");
        txt_ten_doc_gia_tk.setText("");
        txt_CCCD_tk.setText("");
        txt_SDT_tk.setText("");
        txt_dia_chi_tk.setText("");
        txt_nSinh_tk.setText("");
        cb_gioi_tinh_tk.setSelectedItem("");
        cb_trang_thai_tk.setSelectedItem("");
        bt_tk_doc_giaActionPerformed(evt);
// TODO add your handling code here:
    }//GEN-LAST:event_bt_lam_moiActionPerformed

    private void bt_tk_doc_giaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tk_doc_giaActionPerformed
        String ma_doc_gia = txt_ma_doc_gia_tk.getText();
        String ten_doc_gia = txt_ten_doc_gia_tk.getText();
        String so_CCCD= txt_CCCD_tk.getText();
        int gioi_tinh;
        String gt = (String) cb_gioi_tinh_tk.getSelectedItem();
        if(gt.compareTo("")==0){
            gioi_tinh =2;
        }else if(gt.compareTo("Nam")==0){
            gioi_tinh =1;
        }else{
            gioi_tinh=0;
        }
        String ngay_sinh = txt_nSinh_tk.getText();
        String dia_chi = txt_dia_chi_tk.getText();
        String SDT = txt_SDT_tk.getText();
        String trang_thai = (String) cb_trang_thai_tk.getSelectedItem();
        docgiaList = doc_gia_control.getdg_con().timkiemdg(ma_doc_gia, ten_doc_gia, so_CCCD, gioi_tinh, ngay_sinh, dia_chi, SDT, trang_thai);
        doc_gia_control.getdg_con().load_list_tbl(tbl_DS_doc_gia, docgiaList);
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tk_doc_giaActionPerformed

    private void bt_them_dgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_them_dgActionPerformed
        Calendar cl = Calendar.getInstance();
        String ma_doc_gia = txt_ma_doc_gia_tt.getText();
        String ten_doc_gia = txt_ten_doc_gia_tt.getText();
        String so_CCCD = txt_CCCD_tt.getText();
        int gioi_tinh;
        Date ngay_sinh = dc_nSinh_tt.getDate();
        String dia_chi = txt_dia_chi_tt.getText();
        String SDT = txt_SDT_tt.getText(); 
        String trang_thai = (String) cb_trang_thai_tt.getSelectedItem();
        if(rb_nam.isSelected()){
            gioi_tinh = 1;
        }else{
            gioi_tinh=0;
        }
        
        int kt = doc_gia_control.getdg_con().themdg(ma_doc_gia, ten_doc_gia, so_CCCD, gioi_tinh, ngay_sinh, dia_chi, SDT, trang_thai);
        if(kt==1){
            JOptionPane.showMessageDialog(jPanel1, "Thêm thành công");
            
        }else if(kt==2){
            JOptionPane.showMessageDialog(jPanel1, "Thêm không thành công");
        }else if(kt==3){
            JOptionPane.showMessageDialog(jPanel1, "Lỗi mã độc giả");
        }else if(kt==4){
            JOptionPane.showMessageDialog(jPanel1, "Số CCCD đã có");
        }else{
            txt_ma_doc_gia_tt.setText("");
            txt_ten_doc_gia_tt.setText("");
            txt_CCCD_tt.setText("");
            txt_SDT_tt.setText("");
            txt_dia_chi_tt.setText("");
            dc_nSinh_tt.setDate(cl.getTime());
        }
        docgiaList = doc_gia_control.getdg_con().timkiemdg("","","",2,"","", "","");
        doc_gia_control.getdg_con().load_list_tbl(tbl_DS_doc_gia, docgiaList);
// TODO add your handling code here:
    }//GEN-LAST:event_bt_them_dgActionPerformed

    private void bt_luu_dgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_luu_dgActionPerformed
        String ma_doc_gia = txt_ma_doc_gia_tt.getText();
        String ten_doc_gia = txt_ten_doc_gia_tt.getText();
        String so_CCCD = txt_CCCD_tt.getText();
        int gioi_tinh;
        Date ngay_sinh = dc_nSinh_tt.getDate();
        String dia_chi = txt_dia_chi_tt.getText();
        String SDT = txt_SDT_tt.getText(); 
        String trang_thai = (String) cb_trang_thai_tt.getSelectedItem();
        if(rb_nam.isSelected()){
            gioi_tinh = 1;
        }else{
            gioi_tinh=0;
        }
        
        int kt = doc_gia_control.getdg_con().luudg(ma_doc_gia, ten_doc_gia, so_CCCD, gioi_tinh, ngay_sinh, dia_chi, SDT, trang_thai);
        if(kt==1){
            JOptionPane.showMessageDialog(jPanel1, "Thêm thành công");
        }else if(kt==2){
            JOptionPane.showMessageDialog(jPanel1, "Thêm không thành công");
        }else if(kt==3){
            //JOptionPane.showMessageDialog(jPanel1, "ma doc gia khong ton tai");
        }else if(kt==4||kt==7){
            JOptionPane.showMessageDialog(jPanel1, "Lưu thành công");
        }else{
            JOptionPane.showMessageDialog(jPanel1, "Lưu không thành công");
        }
        docgiaList = doc_gia_control.getdg_con().timkiemdg("","","",2,"","", "","");
        doc_gia_control.getdg_con().load_list_tbl(tbl_DS_doc_gia, docgiaList);
// TODO add your handling code here:
    }//GEN-LAST:event_bt_luu_dgActionPerformed

    private void bt_xoa_dgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xoa_dgActionPerformed
        String ma = txt_ma_doc_gia_tt.getText();
        int kt = doc_gia_control.getdg_con().xoadg(ma);
        if(kt==1){
            JOptionPane.showMessageDialog(jPanel1, "Không thể xóa");
        }else if(kt==2){
            JOptionPane.showMessageDialog(jPanel1, "Xóa thành công");
        }else{
            JOptionPane.showMessageDialog(jPanel1, "Không thể xóa");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_bt_xoa_dgActionPerformed

    private void bt_huy_dgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_huy_dgActionPerformed
        Calendar cl = Calendar.getInstance();
        txt_ma_doc_gia_tt.setText("");
        txt_ten_doc_gia_tt.setText("");
        txt_CCCD_tt.setText("");
        txt_SDT_tt.setText("");
        txt_dia_chi_tt.setText("");
        dc_nSinh_tt.setDate(cl.getTime());
        docgiaList = doc_gia_control.getdg_con().timkiemdg("","","",2,"","", "","");
        doc_gia_control.getdg_con().load_list_tbl(tbl_DS_doc_gia, docgiaList);
// TODO add your handling code here:
    }//GEN-LAST:event_bt_huy_dgActionPerformed

    private void tbl_DS_doc_giaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DS_doc_giaMouseClicked
        int index = tbl_DS_doc_gia.getSelectedRow();
        txt_ma_doc_gia_tt.setText(docgiaList.get(index).getMa_doc_gia());
        txt_ten_doc_gia_tt.setText(docgiaList.get(index).getTen_doc_gia());
        txt_CCCD_tt.setText(docgiaList.get(index).getSo_CCCD());
        txt_SDT_tt.setText(docgiaList.get(index).getSDT());
        txt_dia_chi_tt.setText(docgiaList.get(index).getDia_chi());
        dc_nSinh_tt.setDate(docgiaList.get(index).getNgay_sinh());
        cb_trang_thai_tt.setSelectedItem(docgiaList.get(index).getTrang_thai());
        if(docgiaList.get(index).getGioi_tinh()==1){
            rb_nam.setSelected(true);
        }else{
            rb_nu.setSelected(true);
        }
        if(evt.getClickCount()==2&&!evt.isConsumed()){
            
            lich_su_muon_tra.setLocationRelativeTo(null);
            lich_su_muon_tra.setSize(600, 400);
            pmList = doc_gia_control.getdg_con().timpm(docgiaList.get(index).getMa_doc_gia());
            doc_gia_control.getdg_con().load_list_tblpm(tbl_dsPM, pmList);
            txt_dg_pm.setText(docgiaList.get(index).getMa_doc_gia());
            txt_ten_dg_pm.setText(docgiaList.get(index).getTen_doc_gia());
            lich_su_muon_tra.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_DS_doc_giaMouseClicked
    public void load_all(){
        doc_gia_control.getdg_con().load_cb_gt(cb_gioi_tinh_tk);
        doc_gia_control.getdg_con().load_cb_tt(cb_trang_thai_tk);
        doc_gia_control.getdg_con().load_cb_tt(cb_trang_thai_tt);
        Calendar cl = Calendar.getInstance();
        dc_nSinh_tt.setDate(cl.getTime());
        docgiaList = doc_gia_control.getdg_con().timkiemdg("","","",2,"","", "","");
        doc_gia_control.getdg_con().load_list_tbl(tbl_DS_doc_gia, docgiaList);
        txt_ma_doc_gia_tt.setText("");
        txt_ten_doc_gia_tt.setText("");
        txt_CCCD_tt.setText("");
        txt_SDT_tt.setText("");
        txt_dia_chi_tt.setText("");
        txt_ma_doc_gia_tk.setText("");
        txt_ten_doc_gia_tk.setText("");
        txt_CCCD_tk.setText("");
        txt_SDT_tk.setText("");
        txt_dia_chi_tk.setText("");
        txt_nSinh_tk.setText("");
        cb_gioi_tinh_tk.setSelectedItem("");
        cb_trang_thai_tk.setSelectedItem("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_huy_dg;
    private javax.swing.JButton bt_lam_moi;
    private javax.swing.JButton bt_luu_dg;
    private javax.swing.JButton bt_them_dg;
    private javax.swing.JButton bt_tk_doc_gia;
    private javax.swing.JButton bt_xoa_dg;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cb_gioi_tinh_tk;
    private javax.swing.JComboBox<String> cb_trang_thai_tk;
    private javax.swing.JComboBox<String> cb_trang_thai_tt;
    private com.toedter.calendar.JDateChooser dc_nSinh_tt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JDialog lich_su_muon_tra;
    private javax.swing.JRadioButton rb_nam;
    private javax.swing.JRadioButton rb_nu;
    private javax.swing.JTable tbl_DS_doc_gia;
    private javax.swing.JTable tbl_dsPM;
    private javax.swing.JTextField txt_CCCD_tk;
    private javax.swing.JTextField txt_CCCD_tt;
    private javax.swing.JTextField txt_SDT_tk;
    private javax.swing.JTextField txt_SDT_tt;
    private javax.swing.JTextField txt_dg_pm;
    private javax.swing.JTextField txt_dia_chi_tk;
    private javax.swing.JTextField txt_dia_chi_tt;
    private javax.swing.JTextField txt_ma_doc_gia_tk;
    private javax.swing.JTextField txt_ma_doc_gia_tt;
    private javax.swing.JTextField txt_nSinh_tk;
    private javax.swing.JTextField txt_ten_dg_pm;
    private javax.swing.JTextField txt_ten_doc_gia_tk;
    private javax.swing.JTextField txt_ten_doc_gia_tt;
    // End of variables declaration//GEN-END:variables
}
