/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import javax.swing.table.*;
import java.util.*;
import dao.thong_ke_dao;
import java.awt.print.PrinterException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

/**
 *
 * @author minh0
 */
public class fm_thong_ke extends javax.swing.JPanel {
    private List<List<Object>> dausach;
    private List<List<Object>> docgia;
    private DefaultTableModel tblmodel;
    
    /**
     * Creates new form test5_5
     */
    public fm_thong_ke() {
        initComponents();
        initTP();
    }
    public void initTP() {
        Calendar cl =Calendar.getInstance();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        String datef = "01-01-2020";
        date_docgia_kt.setDate(cl.getTime());
        date_sach_kt.setDate(cl.getTime());
        try {
            date_docgia_bd.setDate(dateFormat.parse(datef));
            date_sach_bd.setDate(dateFormat.parse(datef));
        } catch (ParseException ex) {
            Logger.getLogger(fm_thong_ke.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbl_doc_gia.setRowHeight(20);
        tbl_sach.setRowHeight(20);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_doc_gia = new javax.swing.JTable();
        date_docgia_bd = new com.toedter.calendar.JDateChooser();
        date_docgia_kt = new com.toedter.calendar.JDateChooser();
        bt_dg_ms = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bt_sach_muon = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_sach = new javax.swing.JTable();
        date_sach_bd = new com.toedter.calendar.JDateChooser();
        date_sach_kt = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setText("Đến ngày");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tbl_doc_gia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã độc giả", "Tên độc giả", "Số sách đã mượn", "Số lần mượn", "Số sách quá hạn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_doc_gia);

        date_docgia_bd.setDateFormatString("dd/MM/yyyy");

        date_docgia_kt.setDateFormatString("dd/MM/yyyy");

        bt_dg_ms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/xemdiem.png"))); // NOI18N
        bt_dg_ms.setText("Tra cứu");
        bt_dg_ms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_dg_msActionPerformed(evt);
            }
        });

        jLabel1.setText("Từ ngày");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(date_docgia_bd, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(date_docgia_kt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(bt_dg_ms, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(date_docgia_bd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(date_docgia_kt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_dg_ms))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("DS độc giả mượn sách", jPanel1);

        bt_sach_muon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/xemdiem.png"))); // NOI18N
        bt_sach_muon.setText("Tra cứu");
        bt_sach_muon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sach_muonActionPerformed(evt);
            }
        });

        jLabel5.setText("Đến ngày");

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tbl_sach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã đầu sách", "Tên đầu sách", "Số lần mượn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbl_sach);

        date_sach_bd.setDateFormatString("dd/MM/yyyy");

        date_sach_kt.setDateFormatString("dd/MM/yyyy");

        jLabel2.setText("Từ ngày");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(date_sach_bd, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(date_sach_kt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(bt_sach_muon, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bt_sach_muon)
                        .addComponent(date_sach_kt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel2)
                    .addComponent(date_sach_bd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Sách mượn", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_dg_msActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_dg_msActionPerformed
        Date ngaybd = date_docgia_bd.getDate();
        Date ngaykt = date_docgia_kt.getDate();
        docgia = thong_ke_dao.get_TK_dao().TK_doc_gia(ngaybd, ngaykt);
        tblmodel = (DefaultTableModel) tbl_doc_gia.getModel();
        tblmodel.setRowCount(0);
        if(docgia==null){
            
        }else{
            
            for(int i =0 ; i<docgia.size() ; i++){
            tblmodel.addRow(new Object[]{i+1  ,docgia.get(i).get(0) , docgia.get(i).get(1) , docgia.get(i).get(3),
                docgia.get(i).get(2) , docgia.get(i).get(4)});
            }
            
        }
        tbl_doc_gia.setRowHeight(20);
// TODO add your handling code here:
    }//GEN-LAST:event_bt_dg_msActionPerformed

    private void bt_sach_muonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sach_muonActionPerformed
        Date ngaybd = date_sach_bd.getDate();
        Date ngaykt = date_sach_kt.getDate();
        dausach = thong_ke_dao.get_TK_dao().TK_dausach(ngaybd, ngaykt);
        tblmodel = (DefaultTableModel) tbl_sach.getModel();
        tblmodel.setRowCount(0);
        if(dausach==null){
            
        }else{
            for(int i =0 ; i<dausach.size() ; i++){
                tblmodel.addRow(new Object[]{i+1,dausach.get(i).get(0),dausach.get(i).get(1),dausach.get(i).get(2)});
            }
        }
        tbl_sach.setRowHeight(20);
// TODO add your handling code here:
    }//GEN-LAST:event_bt_sach_muonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_dg_ms;
    private javax.swing.JButton bt_sach_muon;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private com.toedter.calendar.JDateChooser date_docgia_bd;
    private com.toedter.calendar.JDateChooser date_docgia_kt;
    private com.toedter.calendar.JDateChooser date_sach_bd;
    private com.toedter.calendar.JDateChooser date_sach_kt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbl_doc_gia;
    private javax.swing.JTable tbl_sach;
    // End of variables declaration//GEN-END:variables
}
